### ISSUE TITLE
Make GVR for app and LabelSelector mutually exclusive

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#684] opened 2020-09-23 11:33 UTC
When we specify application in Service Binding CR, the LocalObjectReference and LabelSelector should be mutually exclusive (https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/apis/operators/v1alpha1/servicebinding_types.go#L71)
According to the API LocalObjectReference is mandatory right now, but to be able to use LabelSelector, it(LocalObjectReference) should be made optional. Or we can be more descriptive(add comments) when we say that LabelSelector is optional, or disable LabelSelector all together. So that folks are accustomed to bind to multiple apps using multiple SBRs.

**Comment by pedjak** [comment] 2021-07-15 17:07
Duplicate of #974

**Closed by pedjak** 2021-07-15 17:07 UTC
