### ISSUE TITLE
error message in status.conditions is not helpful

### ISSUE THREAD

**Issue by kadel** [redhat-developer/service-binding-operator#962] opened 2021-05-14 15:08 UTC
I have probably something wrong with my `ServiceBinding` definition. But problem is that I can't know what as the only message that I can see is "not found". It would be helpful if the message was a little bit more descriptive and mention what SBO can't find.

```
▶ kubectl get servicebindings.binding.operators.coreos.com petclinic-mariadb-mariadb -o yaml
```

``` yaml
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  creationTimestamp: "2021-05-14T14:47:22Z"
  finalizers:
  - finalizer.servicebinding.openshift.io
  generation: 1
  name: petclinic-mariadb-mariadb
  namespace: petclinic
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: petclinic
    uid: 48805ea0-81c1-42e0-ad42-70743bfa14d8
  resourceVersion: "10377"
  uid: 948cba88-0bf4-4051-bddc-d270e64d8f65
spec:
  application:
    group: apps
    name: petclinic
    resource: deployments
    version: v1
  bindAsFiles: false
  detectBindingResources: true
  services:
  - group: mariadb.persistentsys
    kind: MariaDB
    name: mariadb
    namespace: petclinic
    version: v1alpha1
status:
  conditions:
  - lastTransitionTime: "2021-05-14T14:47:23Z"
    message: not found
    reason: ErrorReadingBinding
    status: "False"
    type: CollectionReady
  - lastTransitionTime: "2021-05-14T14:47:23Z"
    message: not found
    reason: ProcessingError
    status: "False"
    type: Ready
  secret: ""
```

Application and service both are correctly defined. I'm not sure what else is SBO trying to find.

```
▶ kubectl get deployments.apps petclinic
NAME        READY   UP-TO-DATE   AVAILABLE   AGE
petclinic   1/1     1            1           111m

▶ kubectl get mariadbs.mariadb.persistentsys mariadb         
NAME      AGE
mariadb   18m
```

<details>
 <summary>operator logs:</summary>

```
{"level":"info","ts":1621004305.6446004,"logger":"controllers.ServiceBinding","msg":"Done","serviceBinding":"petclinic/petclinic-mariadb-mariadb","retry":true,"error":"not found"}
{"level":"error","ts":1621004305.644649,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"binding.operators.coreos.com","reconcilerKind":"ServiceBinding","controller":"servicebinding","name":"petclinic-mariadb-mariadb","namespace":"petclinic","error":"not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/workspace/vendor/github.com/go-logr/zapr/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"}
```
</details>

Running v0.7.1 on minikube

**Comment by pedjak** [comment] 2021-07-15 17:08
Duplicate of #958

**Closed by pedjak** 2021-07-15 17:08 UTC
