### ISSUE TITLE
Broken link in Readme

### ISSUE THREAD

**Issue by kadel** [redhat-developer/service-binding-operator#864] opened 2021-02-05 15:51 UTC
From Readme.md:

> There are multiple methods for making backing services
bindable, including the backing service provider providing metadata as
annotations on the resource. Details on the methods for making backing services bindable
are available in the [Backing Service Provider Best Practices Guide](docs/BackingServiceBestPractices.md)

The link to "Backing Service Provider Best Practices Guide" is broken, and I'm not able to find that document anywhere :-(

**Comment by pedjak** [comment] 2021-02-10 11:08
Duplicate of https://github.com/redhat-developer/service-binding-operator/issues/854

**Closed by pedjak** 2021-02-10 11:08 UTC
Labels: status/duplicate
