### ISSUE TITLE
Remove mechanism to protect against malicious users

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/service-binding-operator#894] opened 2021-03-04 15:26 UTC
Reference EPIC #892 
Use Cases 1

Revert external changes on intermediate binding secret

Reasons:

In order to achieve this, the operator needs to watch on changes on all secrets in a namespace. This generates unnecessary events/reconciliation even when the operator updates/generate the secret. Protection against unauthorized change could be achieved by alternative approach:

Apply more restrictive roles in the namespace
Refactor the implementation in favor of the spec: https://github.com/k8s-service-bindings/spec#role-based-access-control-rbac
Avoid watching for changes in the resources
 
Use Cases 2

Ensure that projections to application are restored, if removed

Reasons:

The operator needs to watch for changes on all application kinds that participate in at least one binding. Such an approach sends to the operator a number of events that correspond to cluster workload - and it can be very high in large/busy clusters. On event receive, the operator needs to list existing service binding and find the one where the given application participates. In most of the cases, there is no binding. This use case puts a high pressure on the operator event queue and it is not scalable.

**Comment by Avni-Sharma** [comment] 2021-03-30 06:51
https://github.com/redhat-developer/service-binding-operator/issues/810 (https://issues.redhat.com/browse/APPSVC-46) looks the same for Use Case 1 

Use case 2 will not hold true currently as watches for application and services have been dropped. Ensure that projections to application are restored, if removed, means we need a reconcile on app change which we are not supporting currently.  We would be supporting the immutability of SBR.

**Comment by baijum** [comment] 2021-03-30 15:25
I agree with what @Avni-Sharma pointed about use case 2. With our current design, we cannot ensure projections to the application are restored if removed.

Looks like use case 1 is a duplicate of #810

**Comment by pedjak** [comment] 2021-03-30 15:50
> Looks like use case 1 is a duplicate of #810

@baijum #810 is about prevent user to modify secrets at the first place. The use case here is about detecting changes and reverting them.

**Comment by Avni-Sharma** [comment] 2021-04-06 08:37
Avoiding watching all resources is the focal point here. Closing this as it has been honored by #903.

**Closed** 2021-04-06 08:37 UTC
Labels: spec
