### ISSUE TITLE
Default Projection as File instead of Env Variables

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/service-binding-operator#893] opened 2021-03-04 15:23 UTC
References EPIC #892

Use case:

Today, our implementation is defaulting projection to environment variables, while the spec requires to project as file. 

Requirements:

Check if this has implication on the documentation side. for all samples we are providing

**Comment by jasperchui** [comment] 2021-03-04 15:24
References EPIC #892

**Comment by DhritiShikhar** [comment] 2021-03-11 12:17
This is a duplicate of #887

**Closed** 2021-03-25 16:59 UTC
Labels: spec
