### ISSUE TITLE
How to parse a json object in binding secret

### ISSUE THREAD

**Issue by s0uravd3** [redhat-developer/service-binding-operator#717] opened 2020-10-07 14:02 UTC
Hi team,
Im trying to create a Service Binding Request using the `redis` bound secret from IBM Cloud. The secret is one json object with `connection` details inside it. Its not as straightforward as the examples where there are separate key-value pairs for each attribute (user, password, host, etc).

Is there a way to parse a `connection` key's json value (similar to jq) and then map the same to a customEnvVar?

Something like : 
```
  customEnvVar:
     - name: REDIS_USER
       value: '{{ index .status.secretName "connection" .jq.rediss.username }}'
     - name: REDIS_PASSWORD
       value: '{{ index .status.secretName "connection" .jq.rediss.password }}'
```

**Comment by baijum** [comment] 2020-10-14 03:23
I have sent a PR to add JSON Path function. #724

I need to write tests and documentation.

**Comment by baijum** [comment] 2020-10-14 03:25
The syntax will be as given in this example script: https://gist.github.com/baijum/4089a736b957a79c508e81ff5eee2824

**Comment by sbose78** [comment] 2020-10-15 15:25
Adding a two-liner in https://github.com/redhat-developer/service-binding-operator/blob/master/docs/application-author.md should suffice too. Thanks!

**Comment by baijum** [comment] 2020-10-15 17:10
> Currently, we have a function to access individual attributes values as JSON objects. Sorry, we don't have documentation. But this PR test cases will give you an idea of how to use it: #412
> 
> The JSONPath PR I sent might give a more expressive syntax. But I think for your use case, that may not be required.

On a closer look, it looks like both `json` and `jsonp` function doesn't provide access to the json objects which are part of the `Secret` data. The current implementation only allows accessing any Kubernetes resource or any nodes within that as a JSON. This needs further investigation.

**Comment by pedjak** [comment] 2021-07-15 16:33
duplicate of #853

**Closed by pedjak** 2021-07-15 16:33 UTC
