### ISSUE TITLE
Custom environment variables should not be prefixed with global prefix

### ISSUE THREAD

**Issue by isutton** [redhat-developer/service-binding-operator#486] opened 2020-05-25 12:51 UTC
#407 has unwillingly changed the behavior of custom environment variables, by prefixing those with the global environment variable prefix if informed.

This behavior should be reverted.

For reference, see https://github.com/redhat-developer/service-binding-operator/issues/475#issuecomment-632638688.

**Comment by sbose78** [comment] 2020-06-23 02:09
Could you please summarize the issue here?

**Comment by DhritiShikhar** [comment] 2020-07-08 07:54
@isutton 

Is this a duplicate of #475 ?

**Comment by Avni-Sharma** [comment] 2020-08-27 06:56
Hi @isutton Do we remove the global envVarPrefix and service's envVarPrefix both, or only the global envVarPrefix? IMO both should be removed, as the custom name should be independent of any prefix as it is custom, however, the issue just mentions Global Prefix, so wanted confirmation in the same regard.

**Comment by isutton** [comment] 2020-08-27 07:17
@Avni-Sharma 

> Hi @isutton Do we remove the global envVarPrefix and service's envVarPrefix both, or only the global envVarPrefix? IMO both should be removed, as the custom name should be independent of any prefix as it is custom, however, the issue just mentions Global Prefix, so wanted confirmation in the same regard.

You're right.

I've just mentioned the global `envVarPrefix` because service's `envVarPrefix` doesn't apply to values applied to `customEnvVar`/`dataMapping`; an entry in `customEnvVar`/`dataMapping` might refer to no services (in the case there's no interpolation in the template) or many services (in the case values from several services are interpolated).

**Comment by Avni-Sharma** [comment] 2020-08-27 07:52
Thanks @isutton

**Closed** 2020-09-11 04:28 UTC
Labels: bug, v0.3.0
