### ISSUE TITLE
Unable to delete a service binding request in spite of setting "ownerReferences"

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/service-binding-operator#542] opened 2020-07-07 06:03 UTC
### Steps to reproduce

1. Create an application based on [this repo](https://github.com/akashshinde/node-todo) using the "Topology" view of DevConsole.
2. Create an EtcdCluster from the Operator, again using "Topology"
3. Get the uid of the node application deployed in Step 1 - `oc get deployment/node-todo -o template="{{.metadata.uid}}"`.
4. Create an SBR with uid from previous step as `ownerReferences` like below:
    ```yaml
    apiVersion: apps.openshift.io/v1alpha1
    kind: ServiceBindingRequest
    metadata:
      name: binding-request
      namespace: myproject
      ownerReferences:
      - apiVersion: apps/v1
        kind: Deployment
        name: node-todo 
        uid: 9075567a-a948-419a-ac28-639f4ca8a2b0
    spec:
      applicationSelector:
        group: apps
        version: v1
        resource: deployments
        resourceRef: node-todo
      backingServiceSelector:
        group: etcd.database.coreos.com
        kind: EtcdCluster
        version: v1beta2
        resourceRef: example
      mountPathPrefix: ""
      customEnvVar: []
      detectBindingResources: true
    ```
5. Delete the `node-todo` deployment using `oc delete deployment/node-todo`.

### Actual behaviour
SBR created using above steps doesn't get deleted in spite of setting `ownerReferences`.

### Expected behaviour
SBR should get deleted

### Note

* If I delete the application using "Topology" view, SBR does get deleted.
* Being able to automatically delete an SBR is important for `odo` because as a part of `odo link`, we are creating an SBR with `ownerReferences` info added (this is not available in `odo`'s master branch; it's on a feature branch on my fork). Upon doing `odo delete`, `odo` deletes the deployment and all the k8s objects that have the deployment set in their `ownerReferences` but SBR doesn't get deleted.

**Comment by DhritiShikhar** [comment] 2020-07-07 06:42
When an application is deleted, ideally a Service Binding Request shouldn't get deleted.

But yes, if we set an ownerReference in SBR explicitly (as you have shown in above), then the SBR should get deleted.

**Comment by DhritiShikhar** [comment] 2020-07-07 06:55
@dharmit 

I quickly tried out this scenario by using a [nodejs+postgreSQL example](https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_postgresql) and setting ownerReference on SBR explicitly. The SBR is deleted successfully when application is deleted -> https://youtu.be/BijY-7oH1Ko

**Comment by dharmit** [comment] 2020-07-07 07:40
@DhritiShikhar Thanks for the recording and prompt response! That was really helpful. The only two differences between what I am doing and what you've recorded are:
1. You're using a different project/application (and this doesn't matter!)
2. You're probably creating the SBR differently than how I am. I'm creating it with `oc create -f /path/to/sbr.yaml` and here's it's YAML:
    ```yaml
    apiVersion: apps.openshift.io/v1alpha1
    kind: ServiceBindingRequest
    metadata:
      creationTimestamp: "2020-07-07T07:16:42Z"
      deletionGracePeriodSeconds: 0
      deletionTimestamp: "2020-07-07T07:20:15Z"
      finalizers:
      - finalizer.servicebindingrequest.openshift.io
      generation: 2
      name: binding-request
      namespace: myproject
      ownerReferences:
      - apiVersion: apps/v1
        kind: Deployment
        name: node-todo
        uid: 64b5c6a7-6fce-41da-aeb6-cf0d940e19d0
      resourceVersion: "560376"
      selfLink: /apis/apps.openshift.io/v1alpha1/namespaces/myproject/servicebindingrequests/binding-request
      uid: c5062d26-f80e-43bf-bcb2-3c2471e0979a
    spec:
      applicationSelector:
        group: apps
        resource: deployments
        resourceRef: node-todo
        version: v1
      backingServiceSelector:
        group: etcd.database.coreos.com
        kind: EtcdCluster
        resourceRef: example
        version: v1beta2
      detectBindingResources: true
    status:
      conditions:
      - lastHeartbeatTime: "2020-07-07T07:16:42Z"
        lastTransitionTime: "2020-07-07T07:16:42Z"
        status: "True"
        type: Ready
      secret: binding-request
    ```

I don't see the `metadata.annotations` in above output like I see in your demo. But, again, I think, this shouldn't matter since `ownerReferences` is set correctly. However, this doesn't work for me:
```sh
$ oc get deployments/node-todo -o template="{{.metadata.uid}}"
c5062d26-f80e-43bf-bcb2-3c2471e0979a

$ oc get sbr/binding-request -o template="{{.metadata.ownerReferences}}"
[map[apiVersion:apps/v1 kind:Deployment name:node-todo uid:c5062d26-f80e-43bf-bcb2-3c2471e0979a]]

$ oc delete deployment/node-todo
deployment.apps "node-todo" deleted

$ oc get sbr
NAME              AGE
binding-request   4m47s

$ oc get sbr/binding-request -o template="{{.metadata.ownerReferences}}"
[map[apiVersion:apps/v1 kind:Deployment name:node-todo uid:c5062d26-f80e-43bf-bcb2-3c2471e0979a]]
```

I'm not sure where to look for this. :confused:

**Comment by DhritiShikhar** [comment] 2020-07-07 07:48
@dharmit Thanks for detailed steps.

Let me try to reproduce this issue by exactly doing it the same way as you have mentioned.

**Comment by DhritiShikhar** [comment] 2020-07-07 08:15
@dharmit I was able to reproduce the issue with the exact steps as you have mentioned - https://youtu.be/PF0xOhsZvxk

**Comment by dharmit** [comment] 2020-07-07 11:04
@DhritiShikhar where do you think the problem stems from? Does this need to be fixed in SBO or some place else? TBH, I'm feeling lost since my understanding is that it's k8s that handles deletion of resources that have `ownerReferences` set.

**Comment by DhritiShikhar** [comment] 2020-07-07 13:27
> I'm feeling lost since my understanding is that it's k8s that handles deletion of resources that have ownerReferences set.

Exactly.

Let me see.

**Comment by Avni-Sharma** [comment] 2020-07-07 16:54
Hi @dharmit . Somehow the sbr's finalisers is not getting deleted in that flow. 
Once I followed your steps, I deleted the deployment. SBR was still there, so I manually removed the finaliser in the sbr and then if you try `oc get sbr`, It will show that sbr is not present, i.e it got deleted.
As a reference I followed the second point mentioned here https://github.com/kubernetes/kubernetes/issues/42594#issuecomment-372840867 .
So as a workaround, if you can check on deleting the finaliser of the SBR if the uid matches. IMO, the finaliser[https://sdk.operatorframework.io/docs/golang/quickstart/#handle-cleanup-on-deletion] concept here is causing issues and nothing else. In a normal native k8s scenario, the ownerRef in itself is sufficient.

**Comment by dharmit** [comment] 2020-07-08 13:05
@Avni-Sharma thanks for looking into this and for your response. However, I'm a bit confused here.

First off, I wasn't aware of the "finalizers" and "initializers" concept till I read your comment. So bear with me if I'm asking something naive.

It took me some time to interpret your comment but in order to "delete the finalizer", I did `oc edit sbr/<name>` and removed the two lines:
```yaml
finalizers:
- finalizer.servicebindingrequest.openshift.io
```
And simply doing that deletes the SBR! Nothing in `oc get sbr` output.

Now, I'm not adding the finalizer in any way. Does it get added automatically upon creation of an SBR? How do I prevent that from happening?

Note that we're trying to automate the deletion of the SBR when we delete a deployment through `odo push`. So this is all happening programmatically and editing the yaml is not a possibility for us. :disappointed:

**Comment by Avni-Sharma** [comment] 2020-07-08 14:09
Hi @dharmit . Yeah, the operator controller sets the finalizers-  https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/servicebinder.go#L277 . 
The investigation should proceed as to why the deletion flow of the service binding operator not reaching in the controller where we are removing the finaliser https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/servicebinder.go#L156 . The cleanup is getting stuck somewhere in https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/servicebinder.go#L135.
Also we can see that once the finaliser is deleted the sbr gets deleted. Because the SBR indeed got the deletionTimeStamp https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/reconciler.go#L203 due to the ownerRef concept.

**Comment by Avni-Sharma** [comment] 2020-07-20 15:19
Hi @dharmit , Can you try this once? A fix has been merged for this

**Comment by Avni-Sharma** [comment] 2020-07-24 18:52
Got a confirmation from @dharmit on this. Works in his setup. :+1:

**Closed** 2020-07-24 18:52 UTC
Labels: bug, priority/high, v0.3.0
