### ISSUE TITLE
Significant memory leaks in SBO

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#605] opened 2020-08-11 14:09 UTC
![Screenshot from 2020-08-10 16-31-48](https://user-images.githubusercontent.com/18097007/89907272-164ab580-dc0a-11ea-928b-df11ca92f8a5.png)

Reported by @bbrowning 
"Every peak of that blue took down an entire Node of the openshift cluster
In my case, as soon as the operator starts up it starts eating up memory."

Slack channel convo link https://coreos.slack.com/archives/CHK22LM6Y/p1597084375063000

**Comment by bbrowning** [comment] 2020-08-11 15:10
It turns out the only reason these peaks are so spaced out is that when the memory leak takes down the Node running the SBO operator pod, another SBO operator pod gets spun up but fails to every acquire the leader lease until I got manually reboot the original failed Node. Once I do that, the memory usage immediately starts ramping up again.

So, the valley between those peaks is only representative of how often I manually reboot a Node.

**Comment by bbrowning** [comment] 2020-08-11 15:43
Here's the memory usage of the service binding operator pod in my cluster for the last 2 hours:

![SBO memory usage](https://user-images.githubusercontent.com/56071/89918216-c0edb480-dbc7-11ea-9989-82812642b769.png)

**Comment by pmacik** [comment] 2020-10-06 22:07
I wasn’t able to reproduce it with the current codebase, but I still have a few theories to check. Anyway, the version 0.3.0 for which this is targeted is a technology preview, for which a non-obvious and non-immediate memory leak is tolerable. I’m lowering a priority of the issue and moving the target version post 0.3.0 release (so that it is resolved in GA).

**Comment by pedjak** [comment] 2020-10-07 11:24
@bbrowning are you still able to reproduce the issue with 0.3.0 version?

**Comment by bbrowning** [comment] 2020-10-14 14:26
I have not reinstalled Service Binding Operator on a long-running cluster because it was causing the entire cluster to become unstable because of this leak. Unfortunately I don't plan to install it on that cluster again until / unless this is confirmed fixed.

**Comment by pedjak** [comment] 2020-10-20 13:49
@bbrowning can you give us a bit more details on the load running on the cluster, so that we can create a similar one and hopefully reproduce the issue?

**Comment by isutton** [comment] 2020-11-26 12:00
I've been slowly experimenting with it, and have a couple of notes to share.

Without any service binding load whatsoever, there's a difference between the configuration used in acceptance tests and production--more specifically the `WATCH_NAMESPACE` environment variable.

With `WATCH_NAMESPACE` set, the system doesn't seem to do anything out of ordinary.

With an empty `WATCH_NAMESPACE` variable, the system starts to behave differently than the previous case; I've observed two things sort of in parallel.

After the operator has started, multiple ConfigMap update events have been observed; some named `*-lock` seem to be used by several subsystems. Compare one of those ConfigMap resources over time:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"crc-tnpk6-master-0_f008bddf-74bd-4f5a-bfb3-dc8e1877ede5","leaseDurationSeconds":15,"acquireTime":"2020-11-23T13:36:59Z","renewTime":"2020-11-26T10:57:42Z","leaderTransitions":10}'
  creationTimestamp: "2020-11-13T11:25:45Z"
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"crc-tnpk6-master-0_f008bddf-74bd-4f5a-bfb3-dc8e1877ede5","leaseDurationSeconds":15,"acquireTime":"2020-11-23T13:36:59Z","renewTime":"2020-11-26T10:58:35Z","leaderTransitions":10}'
  creationTimestamp: "2020-11-13T11:25:45Z"
```

**Comment by isutton** [comment] 2020-12-22 12:59
The behavior of the Service Binding Operator reported in #605 could be verified in a local CRC installation, but not very obvious at first sight.

I’ve consistently degraded the performance of a local CRC cluster, with the following configuration, to the point of not being able to access the API server anymore:

```
$ crc config view
- cpus                                  : 6
- memory                                : 26624
```

As I commented in the issue itself, when the Service Binding Operator is executed to monitor all namespaces within an OpenShift cluster, additional pressure on the operator can be observed since OpenShift and its subsystems use ConfigMaps in certain use cases that require resources to be constantly updated (for example, in the case of hot/cold highly available systems to indicate the hot instance).

Regardless of the resource being constantly updated, there is no hard limitation I’m aware of on how often a resource can be updated.

I’ve observed the operator making the CRC cluster unusable in a freshly installation, and can extrapolate that live clusters, with live traffic, the same would happen.

## Observations

There weren’t a formal, repeatable test other than wiping the cluster and re-execute the acceptance tests due to random failures (for example, random Etcd Operator resources weren’t installed at some point leading to issues like Operator can't restart locally after executing acceptance tests · Issue #786 · redhat-developer/service-binding-operator that after a while couldn’t be reproduced anymore, although the issue might still be there).

To halt the cluster, I’ve executed three times the acceptance tests suite (by executing the suite, removing the test namespace file used by the suite, and re-running the suite-this could be improved by populating the environment variable representing test namespace).

It was observed that the number of work items in the queue (found in the operator’s metrics URL) was growing over time with one worker, whereas when increasing the number of workers, the number of waiting work items decreased considerably.

## Hypothesis

The main factor, which is already being discussed in https://github.com/redhat-developer/service-binding-operator/pull/789, is the fact that by default there’s only one worker available to churn the reconciler’s queue, leading to the observation made above. 

This by itself can lead to a considerable increase of memory usage, since memory needs to be claimed to keep the work items until the sole worker can claim the next item. 

Other than the number of workers, there is also the question of whether predicate functions are not using more memory than they should, and also how they are executed by the Operator SDK runtime.

## Actionables

The number of workers should be set to at least number of available cores plus 1, so there’s at least two workers in any scenario the operator is given one core to use, and also ensures all cores are used in the case more are available.

**Comment by pedjak** [comment] 2021-01-20 10:32
> The number of workers should be set to at least number of available cores plus 1, so there’s at least two workers in any scenario the operator is given one core to use, and also ensures all cores are used in the case more are available.

This got addressed in https://github.com/redhat-developer/service-binding-operator/pull/789

#846 proposes additional actions in order to reduce the pressure on the event queue.

**Closed by pedjak** 2021-01-20 10:32 UTC
Labels: bug
