### ISSUE TITLE
Service Binding Operator goes into a consistently crashlooping state.

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#525] opened 2020-06-26 12:38 UTC
BB:

"I have the service binding operator running in a long-running cluster and the operator itself seems to have recently gone into a consistently crashlooping state. Was there a known breaking change pushed out that my cluster auto-updated to?"

```
{"level":"error","ts":1593174533.6831841,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"UserConfig.redhatcop.redhat.io","error":"no matches for kind \"UserConfig\" in version \"redhatcop.redhat.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go:477"}
{"level":"error","ts":1593174533.6832888,"logger":"main","msg":"Manager exited non-zero","error":"no matches for kind \"UserConfig\" in version \"redhatcop.redhat.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/redhat-developer/service-binding-operator/pkg/log.(*Log).Error\n\t/go/src/github.com/redhat-developer/service-binding-operator/pkg/log/log.go:35\nmain.main\n\t/go/src/github.com/redhat-developer/service-binding-operator/cmd/manager/main.go:152\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

BB: "For some reason the service binding operator is trying to watch some other CRD in my cluster that does not exist?"

SB:"It responds to new incoming OLM-ish CRDs, and adds a watch on them.
When the CRD got removed, it probably continued watching it ?"

SB: "Looks like the https://github.com/operator-framework/community-operators/blob/54b36addd251948e15a2fe4d206534a62e5fab17/upstream-community-operators/quay/1.0.2/quay.v1.0.2.clusterserviceversion.yaml Quay operator was briefly installed.
We should
* install Quay ( or could be anything for that matter )
* remove it
* see what happens.
Could you provide the version of the operator and the version of the cluster you are on?"

**Comment by bbrowning** [comment] 2020-06-26 12:48
This cluster has Service Binding Operator `0.1.1-282` installed. The cluster itself is running OpenShift `4.4.8`.

```
$ oc get csv -n namespace-configuration-operator | grep namespace-configuration
namespace-configuration-operator.v0.1.0     Namespace Configuration Operator    0.1.0                namespace-configuration-operator.v0.0.2   Replacing
namespace-configuration-operator.v0.2.0     Namespace Configuration Operator    0.2.0                namespace-configuration-operator.v0.1.0   Pending
```

That namespace-configuration-operator.v0.2.0 lists 3 CRDs as owned in its CSV file, one of which is the `UserConfig` CRD in the error message above. That operator update is hung for some reason that I'll have to go figure out, but as a result the new CSV (that's still in a Pending state) lists this CRD as owned but the CRD is not actually installed in the cluster.

So, I don't think it has anything to do with Quay. It may be that the service binding operator should ignore any CSVs that aren't in a `Succeeded` state when finding the list of owned CRDs.

**Comment by sbose78** [comment] 2020-06-26 12:52
> I don't think it has anything to do with Quay. 

Yeah, probably not. I just searched on the API group name :)

**Comment by DhritiShikhar** [comment] 2020-06-29 14:26
Conversations around this issue on Slack:

![Screenshot from 2020-06-29 19-55-30](https://user-images.githubusercontent.com/6303309/86018215-a827a600-ba42-11ea-927a-e07073ac3f91.png)

**Comment by baijum** [comment] 2020-09-08 11:37
@bbrowning Can you please confirm, if you still face this issue.

I couldn't reproduce the exact issue. I followed a modified steps to reproduce:

1. Install SBR operator and the example PostgreSQL operator
2. Create a Database CR
3. Create an SBR CR
4. Delete the Database CRD
5. This error will appear on SBR pod log:
```
E0903 17:31:47.616734       1 reflector.go:123] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *unstructured.Unstructured: the server could not find th
e requested resource
```

**Comment by baijum** [comment] 2021-01-06 14:10
The issue is not reproducible as explained in the original issue. The steps I provided in the earlier comment produce a similar error. Since that scenario not very realistic, I would suggest closing this issue.

**Closed by baijum** 2021-01-06 14:10 UTC
Labels: bug, v0.5
